basic_example/CRUDBT/CRUDBT/urls.py
# myproject/urls.py

from django.urls import re_path, include
from django.contrib import admin

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^posts/', include(('posts.urls', 'posts'), namespace='posts')),
]

basic_example/CRUDBT/posts/urls.py
# posts/urls.py
# from django.contrib import admin
# from django.urls import path
from django.urls import re_path
from django.contrib import admin

from posts import views
from posts.views import (
  ListPostView,
  CreatePostView,
  UpdatePostView,
)

urlpatterns = [
    re_path(r'^list-posts/$', ListPostView.as_view(), name='list-posts'),
    re_path(r'^create-post/$', CreatePostView.as_view(), name='create-post'),
    re_path(r'^update-post/(?P<pk>[-\w]+)$', UpdatePostView.as_view(), name='update-post'),
    re_path(r'^delete-post/(?P<pk>[-\w]+)$', views.delete_post, name='delete-post'),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("contact", views.contact, name="contact"),
    path("detail/<str:slug>", views.detail, name="detail"),
    path("search", views.search, name="search"),
    path("<str:slug>", views.category, name="category"),
]

djangoblog/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basic_example/CRUDBT/posts/models.py
# posts/models.py

from __future__ import unicode_literals

from django.db import models
from django.urls import reverse

class Post(models.Model):
  name = models.CharField(max_length=224, null=False, blank=False)
  content = models.TextField(max_length=254, null=False, blank=False)
  timestamp = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)

  def __unicode__(self):
    return self.content

  def get_absolute_url(self):
    return reverse('posts:list-posts', kwargs={})

basic_example/CRUDBT/posts/forms.py
# posts/forms.py

from django import forms
from .models import Post

class CreatePostForm(forms.ModelForm):
  class Meta:
    model = Post
    fields = ['name', 'content',]

CRUDBT/posts/views.py
# posts/views.py

from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse
from django.contrib.messages.views import SuccessMessageMixin
from .forms import CreatePostForm

from .models import Post


class ListPostView(ListView):
    model = Post

    def get(self, request, *args, **kwargs):
        template_name = 'posts/list-posts.html'  # sẽ được tạo ở phần dưới
        obj = {
            'posts': Post.objects.all()
        }
        return render(request, template_name, obj)


class CreatePostView(SuccessMessageMixin, CreateView):
    template_name = 'posts/create-post.html'
    form_class = CreatePostForm
    success_message = 'Crate Post successfully!'


class UpdatePostView(SuccessMessageMixin, UpdateView):
    template_name = 'posts/edit-post.html'
    model = Post
    fields = ['name', 'content', ]
    success_message = 'Update Post successfully!'

    def get_success_url(self):
        return reverse('posts:list-posts', kwargs={})


def delete_post(request, pk):
    post = Post.objects.filter(id=pk)
    post.delete()
    context = {
        "messages": "Delete Post successfully",
        'posts': Post.objects.all()
    }
    return render(request, 'posts/list-posts.html', context)

basic_example/CRUDBT/posts/views.py
# posts/views.py

from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic import ListView, CreateView, UpdateView
from django.urls import reverse
from django.contrib.messages.views import SuccessMessageMixin
from .forms import CreatePostForm

from .models import Post


class ListPostView(ListView):
    model = Post

    def get(self, request, *args, **kwargs):
        template_name = 'posts/list-posts.html'  # sẽ được tạo ở phần dưới
        obj = {
            "messages": "",
            'posts': Post.objects.all()
        }
        return render(request, template_name, obj)

class CreatePostView(SuccessMessageMixin, CreateView):
    template_name = 'posts/create-post.html'
    form_class = CreatePostForm
    success_message = 'Crate Post successfully!'


class UpdatePostView(SuccessMessageMixin, UpdateView):
    template_name = 'posts/edit-post.html'
    model = Post
    fields = ['name', 'content', ]
    success_message = 'Update Post successfully!'

    def get_success_url(self):
        return reverse('posts:list-posts', kwargs={})


def delete_post(request, pk):
    post = Post.objects.filter(id=pk)
    post.delete()
    context = {
        "messages": "Delete Post successfully",
        'posts': Post.objects.all()
    }
    return render(request, 'posts/list-posts.html', context)

basic_example/CRUDBT/posts/templates/posts/create-post.html
<!-- posts/templates/posts/create-post.html -->

{% extends "layouts/layout.html" %}
{% block title %}
    Create Post | {{ block.super }}
{% endblock title %}
{% block content %}
  <h4><small>Create Posts</small></h4>
  <hr>
  <div class="card-body">
    <div class="table-responsive">
      <form action="{% url 'posts:create-post' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="comment">Name<span style="color: red">*</span> :</label>
          <input type="text" class="form-control" rows="5" name="name" required>
        </div>
        <div class="form-group">
          <label for="comment">Content<span style="color: red">*</span> :</label>
          <textarea class="form-control" rows="5" name="content" required></textarea>
        </div>
        <button class="btn btn-secondary" type="submit">Create Post</button>
      </form>
    </div>
  </div>
{% endblock content %}

basic_example/CRUDBT/posts/templates/posts/edit-post.html
<!-- posts/templates/posts/edit-post.html -->

{% extends "layouts/layout.html" %}
{% block title %}
    Edit Post | {{ block.super }}
{% endblock title %}
{% block content %}
  <h4><small>Edit Posts</small></h4>
  <hr>
  <div class="card-body">
    <div class="table-responsive">
      <form action="{% url 'posts:update-post' object.id %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <label for="comment">Name<span style="color: red">*</span> :</label>
          <input type="text" class="form-control" rows="5" name="name" value="{{object.name}}" required>
        </div>
        <div class="form-group">
          <label for="comment">Content<span style="color: red">*</span> :</label>
          <textarea class="form-control" rows="5" name="content" required>{{object.content}}</textarea>
        </div>
        <button class="btn btn-secondary" type="submit">Update Post</button>
      </form>
    </div>
  </div>
{% endblock content %}

basic_example/CRUDBT/posts/templates/posts/list-posts.html
<!-- posts/templates/posts/list-posts.html -->

{% extends "layouts/layout.html" %}
{% block title %}
    List Post | {{ block.super }}
{% endblock title %}
{% block content %}
  <h4><small>List Posts</small></h4>
  <hr>
  {% if posts %}
    {% for post in posts %}
    <h2>{{post.name}}</h2>
    <h5><span class="glyphicon glyphicon-time"></span> Post at {{post.timestamp}}</h5>
    <p>{{post.content}}</p>
    <a href="{% url 'posts:update-post' post.id %}">Edit</a>
    <a href="{% url 'posts:delete-post' post.id %}" onclick="return confirm('Are you sure you want to delete this post?');">Delete</a>
    <br>
    {% endfor %}
  {% else %}
    No post.
  {% endif %}
{% endblock content %}